ame: mlops-linear-regression
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ML Workflow
          pip install -r requirements.txt
          python main.py --run-all
          
          echo '## Validation Metrics for the model
          cat validation_metrics.txt >> model_report.md
          
          cml-publish model_results.png --md >> model_report.md
          
          cml send-comment model_report.md 